import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import './globals.css';

import TopBar from 'components/TopBar';
import Divider from 'components/Divider';
import QueryProvider from 'providers/QueryProvider';
import Main from 'components/Main';

const nunito = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <QueryProvider>
          <Main>
            <TopBar />
            <Divider />
            {children}
          </Main>
        </QueryProvider>
      </body>
    </html>
  );
}
